In [1]:
import nltk
from nltk import WordNetLemmatizer, sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to /home/lenovo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/lenovo/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /home/lenovo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/lenovo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
text = 'AI is changing the way we work. In 2026, NLP systems can analyze emails, websites, and social media posts! But can computers really understand human language? For example, "It\'s amazing," she said. Companies spend $1,299.99 on AI tools, and developers visit https://example.com to learn more. #MachineLearning is everywhere.'

In [4]:
sentences = sent_tokenize(text)
for i in range(len(sentences)):
    print(f"Sentence number {i + 1}: ",sentences[i])

Sentence number 1:  AI is changing the way we work.
Sentence number 2:  In 2026, NLP systems can analyze emails, websites, and social media posts!
Sentence number 3:  But can computers really understand human language?
Sentence number 4:  For example, "It's amazing," she said.
Sentence number 5:  Companies spend $1,299.99 on AI tools, and developers visit https://example.com to learn more.
Sentence number 6:  #MachineLearning is everywhere.

In [5]:
tokens = word_tokenize(text)
for w in range(len(tokens)):
    print(f"word number {w + 1}: {tokens[w]}")

word number 1: AI
word number 2: is
word number 3: changing
word number 4: the
word number 5: way
word number 6: we
word number 7: work
word number 8: .
word number 9: In
word number 10: 2026
word number 11: ,
word number 12: NLP
word number 13: systems
word number 14: can
word number 15: analyze
word number 16: emails
word number 17: ,
word number 18: websites
word number 19: ,
word number 20: and
word number 21: social
word number 22: media
word number 23: posts
word number 24: !
word number 25: But
word number 26: can
word number 27: computers
word number 28: really
word number 29: understand
word number 30: human
word number 31: language
word number 32: ?
word number 33: For
word number 34: example
word number 35: ,
word number 36: ``
word number 37: It
word number 38: 's
word number 39: amazing
word number 40: ,
word number 41: ''
word number 42: she
word number 43: said
word number 44: .
word number 45: Companies
word number 46: spend
word number 47: $
word number 48: 1,299.99
word number 49: on
word number 50: AI
word number 51: tools
word number 52: ,
word number 53: and
word number 54: developers
word number 55: visit
word number 56: https
word number 57: :
word number 58: //example.com
word number 59: to
word number 60: learn
word number 61: more
word number 62: .
word number 63: #
word number 64: MachineLearning
word number 65: is
word number 66: everywhere
word number 67: .

In [6]:
stop_words = stopwords.words("english")

In [7]:
content_words = [token for token in tokens
                 if token.isalpha() and token not in stop_words]

In [8]:
stop_words_found = [token for token in tokens
                    if token.isalpha() and token in stop_words]

In [9]:
stemmer = nltk.PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in content_words]

In [10]:
content_words[5:15]

['NLP',
 'systems',
 'analyze',
 'emails',
 'websites',
 'social',
 'media',
 'posts',
 'But',
 'computers']

In [11]:
stemmed_words[5:15]

['nlp',
 'system',
 'analyz',
 'email',
 'websit',
 'social',
 'media',
 'post',
 'but',
 'comput']

In [12]:
lem = WordNetLemmatizer()

In [13]:
[lem.lemmatize(word, pos="v") for word in content_words][:10]

['AI',
 'change',
 'way',
 'work',
 'In',
 'NLP',
 'systems',
 'analyze',
 'email',
 'websites']

In [14]:
[lem.lemmatize(word, pos="a") for word in content_words][:10]

['AI',
 'changing',
 'way',
 'work',
 'In',
 'NLP',
 'systems',
 'analyze',
 'emails',
 'websites']

In [15]:
[lem.lemmatize(word, pos="r") for word in content_words][:10]

['AI',
 'changing',
 'way',
 'work',
 'In',
 'NLP',
 'systems',
 'analyze',
 'emails',
 'websites']

In [16]:
text = "The children were running faster than the mice, and they studied, studies, and studied the lessons while the better students were writing and writing."

In [17]:
content_words = word_tokenize(text)
stop_words = stopwords.words("english")
filtered_tokens = [token for token in content_words if token.isalpha() and token not in stop_words]
lemmatizer = WordNetLemmatizer()
lemmatizer_verb = [lemmatizer.lemmatize(word, pos="v") for word in filtered_tokens]

In [18]:
lemmatizer_noun = [lemmatizer.lemmatize(word, pos="n")
                   for word in filtered_tokens]

In [19]:
lemmatizer_adjective = [lemmatizer.lemmatize(word, pos = "a")
                        for word in filtered_tokens]

In [20]:
lemmatizer.lemmatize("activating", pos="a")

'activating'

In [21]:
documents = [
    "I love machine learning and NLP.",
    "Machine learning is powerful.",
    "NLP helps computers understand human language.",
    "I love learning new things about AI."
]

In [22]:
count_vectorizer = CountVectorizer()

In [23]:
document_matrix = count_vectorizer.fit_transform(documents)

In [24]:
print(count_vectorizer.get_feature_names_out())

['about' 'ai' 'and' 'computers' 'helps' 'human' 'is' 'language' 'learning'
 'love' 'machine' 'new' 'nlp' 'powerful' 'things' 'understand']

In [25]:
count_vectorizer.vocabulary_

{'love': 9,
 'machine': 10,
 'learning': 8,
 'and': 2,
 'nlp': 12,
 'is': 6,
 'powerful': 13,
 'helps': 4,
 'computers': 3,
 'understand': 15,
 'human': 5,
 'language': 7,
 'new': 11,
 'things': 14,
 'about': 0,
 'ai': 1}

In [26]:
document_matrix.shape #Reurns (4, 16) that means there are four sentences and 16 words

(4, 16)

In [27]:
doc_array = document_matrix.toarray()

In [28]:
import pandas as pd

matrix_df = pd.DataFrame(doc_array, columns =count_vectorizer.get_feature_names_out())
matrix_df

,about,ai,and,computers,helps,human,is,language,learning,love,machine,new,nlp,powerful,things,understand
0,0,0,1,0,0,0,0,0,1,1,1,0,1,0,0,0
1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0
2,0,0,0,1,1,1,0,1,0,0,0,0,1,0,0,1
3,1,1,0,0,0,0,0,0,1,1,0,1,0,0,1,0

In [31]:
test_text = ["I love machine learning and deep leanring a lot",
             "I wish I could start my personal business ASAP",
             "computers helps me learn nlp"]

print(count_vectorizer.transform(test_text))

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (3, 16)>
  Coords	Values
  (0, 2)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (2, 3)	1
  (2, 4)	1
  (2, 12)	1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

In [37]:
tfidf_vectorizer.vocabulary_

{'love': 9,
 'machine': 10,
 'learning': 8,
 'and': 2,
 'nlp': 12,
 'is': 6,
 'powerful': 13,
 'helps': 4,
 'computers': 3,
 'understand': 15,
 'human': 5,
 'language': 7,
 'new': 11,
 'things': 14,
 'about': 0,
 'ai': 1}

In [48]:
feature_names  = tfidf_vectorizer.get_feature_names_out()
print(feature_names )

['about' 'ai' 'and' 'computers' 'helps' 'human' 'is' 'language' 'learning'
 'love' 'machine' 'new' 'nlp' 'powerful' 'things' 'understand']

In [50]:
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns = feature_names).round(2)
tfidf_df

,about,ai,and,computers,helps,human,is,language,learning,love,machine,new,nlp,powerful,things,understand
0,0.00,0.00,0.55,0.00,0.00,0.00,0.00,0.00,0.35,0.44,0.44,0.00,0.44,0.00,0.00,0.00
1,0.00,0.00,0.00,0.00,0.00,0.00,0.57,0.00,0.37,0.00,0.45,0.00,0.00,0.57,0.00,0.00
2,0.00,0.00,0.00,0.42,0.42,0.42,0.00,0.42,0.00,0.00,0.00,0.00,0.33,0.00,0.00,0.42
3,0.45,0.45,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.35,0.00,0.45,0.00,0.00,0.45,0.00